name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1sSYxbZ7HGNSp5iqx51RHAMrZur_4aGrEQkESjAPv39QcP1yY
        USER_PASS: admin
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
